### ISSUE TITLE
スクロール直後に何も表示されないことがある

### ISSUE THREAD

**Issue by ginpei** [decomoji/decomoji-finder#15]
v2.2+

素早くかつ遠目にスクロールすると、一瞬真っ白になり遅れて一覧が表示される。

### 対応案

virtual-scroll を差し替えて現在の recycle じゃなくて lazy なやり方、遅延生成するが一度生成したものは消さずに残すようにしたい。一度生成したものを破棄する必要はなさそうに見える<sup>[要検証]</sup>ので。
​
そのやり方なら一度表示した箇所は既に生成、配置済みなのでそのまま瞬時に再表示される。加えて、スクロール前に負荷をかけない程度に先行して生成していくと、初めて表示する箇所も同様高速化される見込み。

**Comment by oti** [comment]
触ってる感じもう起きてないように見えるので一旦 close しま。
