### ISSUE TITLE
表示量が多いと画像の描画が遅い

### ISSUE THREAD

**Issue by ginpei** [decomoji/decomoji-finder#16]
例えばサイズを 16px にして大きな画面で開くと大量のデコモジボタンが表示され、その際特に画像の描画が遅く CPU 負荷も高い。どうにかしたい。

### 対応案

画像をスプライト化する。

とりあえずこれで本現象が改善することは確認した。`test/sprite` ブランチ参照。

しかしまだ課題がある。

- Extra だけで 5,000 個あり、これをまとめると 12 MB 程度
- 分割するとスプライト画像とデコモジの対応表が必要になる
- 分割単位どうする
- 上記課題対応も含めたスプライト画像生成の自動化

調査が必要なもの

- ファイルサイズどの程度が許容範囲なのか。サイズと数のバランス

**Comment by ginpei** [comment]
画像以外はあまりやれることが思いつかないです。

performance 計測するとスクリプト実行にそれなりの時間が取られていて、つまり Vue.js が頑張ってるということです。それについて 1. 画像を削る 2. その他全部削って単純な要素にする を試したところ大差なくて、Vue.js であの量を生成するのがもう遅いって感じがします。

遅いといってもそこまででもない……気がする……のでたぶん大丈夫。

**Comment by oti** [comment]
`buffer` プロパティで表示パフォーマンスが改善するかもしれないとの由。

**Comment by oti** [comment]
#20

**Comment by ginpei** [comment]
https://github.com/Akryum/vue-virtual-scroller#props

> buffer (default: 200): amount of pixel to add to edges of the scrolling visible area to start rendering items further away.

スクロール時に先行読み込みする量みたいですね。順次スクロールする操作で有効な気がします。

**Comment by oti** [comment]
https://github.com/decomoji/finder/commit/f34e66d9593ffbc639a05d0b1a838fbf5c5c410e で画面高の半分を `buffer` に指定するようにしてみました。普通のスクロール速度なら画像の描画に遅延はなくなったように思います。
